import { useEffect, useMemo, useRef, useState } from 'react';
import { AccessibilityInfo, findNodeHandle, Linking, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useReducedMotion } from 'react-native-reanimated';
import type { StudyProvider } from '.';
import { bookName } from '../text/canon';
import { tokens } from '../ui/tokens';
import { ResourceText } from './ResourceText';

export function DictionaryLibrary({ study, book }: { study:StudyProvider; book:string }) {
  const reducedMotion=useReducedMotion();
  const openerRef=useRef<View>(null); const modalRef=useRef<View>(null);
  const [open,setOpen]=useState(false); const [query,setQuery]=useState(''); const [debouncedQuery,setDebouncedQuery]=useState('');
  const [articleId,setArticleId]=useState<string|null>(null); const [notices,setNotices]=useState(false); const [showBook,setShowBook]=useState(false);
  useEffect(()=>{const timer=setTimeout(()=>setDebouncedQuery(query),200);return()=>clearTimeout(timer);},[query]);
  const results=useMemo(()=>study.search(debouncedQuery),[debouncedQuery,study]);
  const article=articleId?study.article(articleId):null;
  const bookResources=useMemo(()=>open&&showBook?study.bookResources(book):[],[book,open,showBook,study]);
  const close=()=>{setOpen(false);setArticleId(null);setNotices(false);setShowBook(false);setTimeout(()=>{const handle=findNodeHandle(openerRef.current);if(handle)AccessibilityInfo.setAccessibilityFocus(handle);},100);};
  return <>
    <Pressable ref={openerRef} accessibilityRole="button" accessibilityLabel="Open study library" style={styles.open} onPress={()=>setOpen(true)}><Text style={styles.openTitle}>Open study library</Text><Text style={styles.muted}>Search 6,000+ Tyndale dictionary articles offline</Text></Pressable>
    <Modal visible={open} animationType={reducedMotion?'none':'slide'} onShow={()=>{const handle=findNodeHandle(modalRef.current);if(handle)AccessibilityInfo.setAccessibilityFocus(handle);}} onRequestClose={close}><View style={styles.modal} accessibilityViewIsModal>
      <View ref={modalRef} accessible accessibilityRole="header" accessibilityLabel="Study library" />
      <View style={styles.head}><Pressable accessibilityRole="button" accessibilityLabel={articleId?'Back to study library':'Close study library'} style={styles.control} onPress={()=>articleId?setArticleId(null):close()}><Text style={styles.link}>{articleId?'Back':'Close'}</Text></Pressable><Text accessibilityRole="header" style={styles.title}>{article?.title??'Study library'}</Text><Pressable accessibilityRole="button" accessibilityLabel="Show source and licence" style={styles.control} onPress={()=>setNotices((value)=>!value)}><Text style={styles.link}>Source</Text></Pressable></View>
      {notices?<ScrollView contentContainerStyle={styles.content}><Text accessibilityRole="header" style={styles.subhead}>Tyndale Open Resources</Text><Text style={styles.body}>Adapted from Tyndale Open Study Notes. The original work by Tyndale House Publishers is available for free at http://www.tyndaleopenresources.com.</Text><Text style={styles.body}>Adapted from Tyndale Open Bible Dictionary. The original work by Tyndale House Publishers is available for free at http://www.tyndaleopenresources.com.</Text><Text style={styles.body}>Copyright © 2022–2023 Tyndale House Publishers. Resource data is licensed under Creative Commons Attribution-ShareAlike 4.0. XML was converted to structured JSON; search keys and references were normalized; maps, pictures, charts, and supplemental textboxes were omitted.</Text><Pressable accessibilityRole="link" accessibilityLabel="Open Tyndale Open Resources website" style={styles.open} onPress={()=>void Linking.openURL('https://tyndaleopenresources.com/')}><Text style={styles.openTitle}>Open the original resources</Text></Pressable><Pressable accessibilityRole="link" accessibilityLabel="Read Creative Commons Attribution ShareAlike 4.0 licence" style={styles.open} onPress={()=>void Linking.openURL('https://creativecommons.org/licenses/by-sa/4.0/')}><Text style={styles.openTitle}>Read the CC BY-SA 4.0 licence</Text></Pressable></ScrollView>
      :article?<ScrollView contentContainerStyle={styles.content}><ResourceText content={article.content} onOpenArticle={setArticleId}/><Text style={styles.attribution}>{study.attribution()}</Text></ScrollView>
      :<View style={styles.flex}><Pressable accessibilityRole="button" accessibilityLabel={`${showBook?'Hide':'Show'} introduction to ${bookName(book)}`} style={styles.bookButton} onPress={()=>setShowBook((value)=>!value)}><Text style={styles.openTitle}>{showBook?'Hide':`About ${bookName(book)}`}</Text></Pressable>{showBook?<ScrollView contentContainerStyle={styles.content}>{bookResources.map((resource)=><View key={resource.id} style={styles.resource}><Text accessibilityRole="header" style={styles.subhead}>{resource.title}</Text><ResourceText content={resource.content}/></View>)}</ScrollView>:<><TextInput accessibilityLabel="Search the Tyndale Bible Dictionary" value={query} onChangeText={setQuery} placeholder="Search the Bible dictionary" placeholderTextColor={tokens.color.ink40} style={styles.input}/><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.results}>{query.length>0&&results.length===0?<Text style={styles.muted}>No dictionary entry matches this search.</Text>:results.map((result)=><Pressable accessibilityRole="button" accessibilityLabel={`Open dictionary article ${result.title}`} key={result.id} style={styles.result} onPress={()=>setArticleId(result.id)}><Text style={styles.resultTitle}>{result.title}</Text></Pressable>)}</ScrollView></>}</View>}
    </View></Modal>
  </>;
}

const styles=StyleSheet.create({open:{minHeight:44,borderWidth:1,borderColor:tokens.color.ink15,borderRadius:12,padding:16,gap:4},openTitle:{fontFamily:tokens.font.display,fontSize:16,fontWeight:'800',color:tokens.color.ink},muted:{fontFamily:tokens.font.display,fontSize:13,color:tokens.color.ink60},modal:{flex:1,backgroundColor:tokens.color.paper,paddingTop:48},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:tokens.color.ink15,paddingHorizontal:14},control:{minWidth:56,minHeight:48,justifyContent:'center'},link:{fontFamily:tokens.font.display,color:tokens.color.thread,fontWeight:'700'},title:{flex:1,textAlign:'center',fontFamily:tokens.font.display,fontWeight:'900',fontSize:19,color:tokens.color.ink},flex:{flex:1},bookButton:{marginHorizontal:20,marginTop:16,minHeight:48,justifyContent:'center',borderBottomWidth:1,borderColor:tokens.color.ink15},input:{margin:20,minHeight:48,borderWidth:1,borderColor:tokens.color.ink15,borderRadius:12,paddingHorizontal:14,fontFamily:tokens.font.display,fontSize:16,color:tokens.color.ink},results:{paddingHorizontal:20,paddingBottom:40},result:{minHeight:48,justifyContent:'center',borderBottomWidth:1,borderColor:tokens.color.ink15},resultTitle:{fontFamily:tokens.font.display,fontSize:16,color:tokens.color.ink},content:{padding:24,gap:16},resource:{gap:10,borderBottomWidth:1,borderColor:tokens.color.ink15,paddingBottom:18},subhead:{fontFamily:tokens.font.display,fontSize:22,fontWeight:'900',color:tokens.color.ink},body:{fontFamily:tokens.font.display,fontSize:15,lineHeight:23,color:tokens.color.ink},attribution:{fontFamily:tokens.font.mono,fontSize:10,lineHeight:16,color:tokens.color.ink40,marginTop:16}});
